# -*- coding: utf-8 -*-
#################################################################################
#
#    (DC)² - DataCenter Deployment Control
#    Copyright (C) 2010, 2011, 2012  Stephan Adig <sh@sourcecode.de>
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#################################################################################

#
# Std. Python Libs
#
import sys
import types
import xmlrpclib
import re
import uuid


try:
    import web
except ImportError:
    print "You don't have web.py installed"
    sys.exit(1)

try:
    from dc2.lib.db.mongo import Database
    from dc2.lib.db.mongo import Table
    from dc2.appserver.helpers import check_record
    from dc2.appserver.rpc import rpcmethod
except ImportError:
    print "You don't have DC² correctly installed"
    sys.exit(1)

try:
    from settings import MONGOS
except ImportError:
    print "You don't have a settings file"
    sys.exit(1)


tbl_server = Table(MONGOS["dc2db"]["database"].get_table("servers"))
tbl_macs = Table(MONGOS["dc2db"]["database"].get_table("mac_addresses"))



@rpcmethod(name="dc2.deployment.utils.udev.persistent_net_rules",params={},returns={},is_xmlrpc=True,is_jsonrpc=True)
def dc2_deployment_os_udev_network(record=None):
    if record is not None and type(record) is types.DictType:
        if record.has_key("_id") or record.has_key("serial_no"): 
            server_rec=tbl_server.find_one(record)
            if server_rec is not None:
                mac_list=tbl_macs.find({"server_id":server_rec["_id"]})
                udev_rules_file="#\n#Generated By DC2\n#Don't edit this file manually\n#\n"
                if mac_list is not None and len(mac_list)>0:
                    for mac in mac_list:
                        line='SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="%s",ATTR{dev_id}="0x0",ATTR{type}=="1",KERNEL=="eth*",NAME="%s"\n' % (mac["mac_addr"],mac["device_name"])
                        udev_rules_file=udev_rules_file+line
                    return udev_rules_file
                        
                        
                        
                        
