#! /bin/bash

# (c) Michael Goetze, 2010-2011, mgoetze@mgoetze.net

$ROOTCMD /sbin/MAKEDEV urandom
$ROOTCMD /sbin/MAKEDEV random
$ROOTCMD /sbin/MAKEDEV -m 16 hda 
$ROOTCMD /sbin/MAKEDEV sda
$ROOTCMD /sbin/MAKEDEV sdb
$ROOTCMD /sbin/MAKEDEV rtc
$ROOTCMD /sbin/MAKEDEV cciss


