#!/bin/bash

set -a

# Get Real MAC Address from the PXE Boot Device 
REAL_MAC=`echo $BOOTIF|sed -e "s/^01-//"|sed -e "s/-/\:/g"`

if [ "$FAI_ACTION" == "install" ]; then
        dc2-client -i --installstatus-find=mac --installstatus-find-value="${REAL_MAC}" --installstatus-update-progress="Deployment" --dc2-backend-url="${DC2_BACKEND_URL}"
        hostclasses=`dc2-client -h --host-find=mac --host-find-value="${REAL_MAC}" --host-output-value=hostclasses --dc2-backend-url="${DC2_BACKEND_URL}"`
        my_hostname=`dc2-client -h --host-find=mac --host-find-value="${REAL_MAC}" --host-output-value=hostname --dc2-backend-url="${DC2_BACKEND_URL}"`
        my_domainnanme=`dc2-client -h --host-find=mac --host-find-value="${REAL_MAC}" --host-output-value=domainname --dc2-backend-url="${DC2_BACKEND_URL}"`
        hostname -b ${my_hostname}
        hostname ${my_hostname}
        echo $hostclasses
fi

