#!/bin/bash                                                                                                                                                                                                                                  
dc2-client --do-inventory --dc2-backend-url=$DC2_BACKEND_URL
# faireboot

